### PR TITLE
Monorepo (Part 1)

### PR DESCRIPTION
**Pull request by viktor44**
### What is this PR

It is the first step of the new project structure work (see https://github.com/getstation/desktop-app#workspace-management-todo)

* Enabled yarn workspaces in `package.json`
* Moved `appstore` to the `packages` folder

### TODO:

* Test failures have to be fixed

```log
 FAIL  test/jest/persistence/test-password-managers.ts

  ● Password Manager Config › db is empty
```

### CODE REVIEW

**Comment by magne4000** [comment]
Migrating to monorepo for `appstore`, `sdk` and `theme` could indeed simplify things a little.
I would recommend migrating from `yarn` to `pnpm` though, as yarn workspaces is not really robust (and pnpm is faster, so that a plus).
I think it will not be straightforward though.

**Comment by viktor44** [comment]
I've added `lerna`
Am I right that we have to use `lerna` to run scripts?
I mean `lerna run dev` instead of `yarn run dev` and so on?

**Comment by magne4000** [comment]
With yarn workspaces yes. If you use pnpm you could just use `pnpm -r`

**Comment by viktor44** [comment]
> With yarn workspaces yes

Migration to `pnpm` is a separate task which is not easy.

**Pull request closed without merging**
