### PR TITLE
support multiple account in google chat

### LINKED ISSUE #227: Google Chat / Hangouts doesn't support multiple accounts
- Application version: 2.5.0
 - OS: MacOS 14

**Steps to Reproduce:**

For Gmail or Calendar, I can have 2 services for each account and I'll have the image of the account in the service icon.

For Hangouts / Chat:
* the image is not show (see screenshot)
* I cannot switch from one account to another (it opens a new window with the new account, but it's forgotten when I close the new window)

**Screenshots**
image

### PR DESCRIPTION
**Pull request by 3nids**
fix #227

### CODE REVIEW

**Comment by 3nids** [comment]
successfully compiled and tested:
image

**Comment by viktor44** [comment]
That's great!
Thank you

**Comment by 3nids** [comment]
@viktor44 thanks for the quick response! Is there a release schedule somehwere? what is the policy regarding bugfix releases?

**Comment by viktor44** [comment]
I am currently trying to build release once in a month.
But it is not a strict rule.

**Comment by 3nids** [comment]
@viktor44 any chance to trigger a new release soon? :)
cheers

**Pull request merged**
