### PR TITLE
Mastodon app needs flexibility for server choice #167

### LINKED ISSUE #167: Mastodon app needs flexibility for server choice
The current Mastodon app is tied to mastodon.social – it needs to prompt the user for the server URL at the same time as prompting for login details.

### PR DESCRIPTION
**Pull request by viktor44**
### What is this PR

* Fixed #167
* Added custom server for **Zenhub** application

**Problem:** Cached manifests are not refreshed. 

How to refresh this cache? 
Do we need caching at all since we are using local data?

### CODE REVIEW

**Comment by viktor44** [comment]
> What do you mean by that?

Test case:
1. Add Zenhub application to Station (manifest ver.1)
2. Remove Zenhub application
3. Close Station
4. Change manifest (ver.2)
5. Run Station
6. Add Zenhub application to Station 

**Error**: Station uses manifest ver.1 because it is cached in `ApplicationManifestsCache` folder

**Comment by magne4000** [comment]
Oh yes indeed, it's an artifact dating from the time where manifest were downloaded from the online appstore. The whole `ApplicationManifestsCache` layer should be removable without issue now.

**Comment by viktor44** [comment]
I got rid of the local cache folder usage.
Review it please when you get a chance

**Comment by magne4000** [comment]
LGTM!

**Pull request merged**
