### PR TITLE
Fix for "Google signin no longer works since 2.7.0 on Mac" #311

### PR DESCRIPTION
**Pull request by viktor44**
Workaround for new problem.
`session.webRequest.onBeforeSendHeaders(` is never called for any session except default. `session.webRequest.onBeforeRequest(` works as expected.
Don't understand what I'm doing wrong. Any ideas would be very appreciated.
So for sessions with `partition` attribute we don't replace header and can't login with Google.

### CODE REVIEW

**Comment by magne4000** [comment]
Here are some places you could check. My guess is that there is some part of the current code that only handles `defaultSession`, and would need to be adapted for all sessions.
- https://github.com/getstation/desktop-app/blob/f86cc5718e1284088805a7fc1c7a1af45f8e8792/app/services/services/session/main.ts#L8-L40
- https://github.com/getstation/desktop-app/blob/f86cc5718e1284088805a7fc1c7a1af45f8e8792/app/services/services/download/main.ts#L118-L133
- https://github.com/getstation/desktop-app/blob/f86cc5718e1284088805a7fc1c7a1af45f8e8792/app/services/services/tab-webcontents/main.ts#L203
- https://github.com/getstation/desktop-app/blob/f86cc5718e1284088805a7fc1c7a1af45f8e8792/app/services/services/url-router-helper/lib.ts#L28
- https://github.com/getstation/desktop-app/blob/f86cc5718e1284088805a7fc1c7a1af45f8e8792/app/services/services/tab-webcontents/api.ts#L154
- https://github.com/getstation/desktop-app/blob/f86cc5718e1284088805a7fc1c7a1af45f8e8792/app/sdk/session/SessionProvider.ts#L36-L58
  - If after investigation it appears that this is where it seems to be missing something, let me know. We will need to implement [SessionService](https://github.com/getstation/desktop-app/blob/f86cc5718e1284088805a7fc1c7a1af45f8e8792/app/services/renderer/index.ts#L67) for all sessions, and not only for `defaultSession`.

**Comment by viktor44** [comment]
@magne4000 would you if I merge the PR?
The bug is quite critical and I want to release v2.7.1 because of it

**Comment by viktor44** [comment]
> but if there are some new things critical breaking, we should reverse to always use defaultSession until a proper fix is found.

Agree. But IMO not now.
I've checked our top 30 apps and they work fine.


> Have you managed to reproduce the issue with a fresh Electron boilerplate? Because it indeed could be an Electron issue in itself, but we need to be sure.

Not yet.

**Comment by viktor44** [comment]
> Have you managed to reproduce the issue with a fresh Electron boilerplate? Because it indeed could be an Electron issue in itself, but we need to be sure.

I've created a small test and everything is working fine. The bug does not exists in the clean Electron. 😢 
So the problem is somewhere in our code. That's a bad news. I have no idea how to trace it.

**Pull request merged**
